# Change these first
owner: ptstaiwan-bot # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: 公共電視
    url: https://www.pts.org.tw/
  - name: 公視+
    url: https://www.ptsplus.tv/
  - name: 公視新聞網
    url: https://news.pts.org.tw/
  - name: PeoPo 公民新聞
    url: https://www.peopo.org/
  - name: 公視之友
    url: https://friends.pts.org.tw/
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: newmedia.pts.org.tw
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
